server:
  port: 8070 
spring:
  cloud:
    config:
      enabled: true
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers:
    - localhost:19091
#http://localhost:8761/eureka/apps/org-orchestration
eureka: 
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'
#Below is required if we are not using Eureka naming server
#employee-management:
  #ribbon:
    #listOfServers: http://localhost:8080,http://localhost:8081
