server:
  port: 8070 
spring:
  cloud:
    config:
      enabled: true
#http://localhost:8761/eureka/apps/org-orchestration
eureka: 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'