server:
  port: 8080
spring:
  cloud:
    config:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'