# Look at the docker-compose.yml files to see other required parameters. 
# Other required parameters has been passed as docker-compose environment variables
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: warn