server:
  servlet:
    context-path: /employee
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empmgmt
    username: nitin
    password: ENC(q9Ol5HJ6ZzvZaTikm8d6nKKrQH0qLQFb)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'