version: '3'
services:
   db:
      image: mysql:8
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: pass
         MYSQL_DATABASE: empmgmt
         MYSQL_USER: nitin
         MYSQL_PASSWORD: password
      volumes:
      - ../mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
      ports:
      - 3306:3306
   config-server:
      image: tonitingaurav/configuration-server
      restart: always
      ports:
      - 8888:8888
      environment:
         JAVA_OPTS: '-Djasypt.encryptor.password=jasy-config-app'