version: '3'
services:
   db:
      image: mysql:8
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: pass
         MYSQL_DATABASE: empmgmt
         MYSQL_USER: nitin
         MYSQL_PASSWORD: password
      volumes:
      - ../mysql:/var/lib/mysql
      # Make sure that ../mysql is emptry first time if you want to execute init scripts
      - ./initdb:/docker-entrypoint-initdb.d
      ports:
      - 3306:3306
   config-server:
      image: tonitingaurav/configuration-server
      restart: always
      ports:
      - 8888:8888
      environment:
         JAVA_OPTS: '-Djasypt.encryptor.password=jasy-config-app'
   discovery-server:
      image: tonitingaurav/discovery-server
      restart: always
      ports:
      - 8761:8761