version: '3.7'
services:
   zookeeper-1:
      extends:
         file: ../common/docker-compose.yml
         service: zookeeper-1
      volumes:
      - ../data/dev/zk/data:/var/lib/zookeeper/data
      - ../data/dev/zk/logs:/var/lib/zookeeper/log
   kafka-1:
      extends:
         file: ../common/docker-compose.yml
         service: kafka-1
      depends_on:
      - zookeeper-1
      volumes:
      - ../data/dev/kafka/data:/var/lib/kafka/data
   zipkin:
      extends:
         file: ../common/docker-compose.yml
         service: zipkin
      depends_on:
      - "kafka-1"
   db:
      extends:
         file: ../common/docker-compose.yml
         service: db
      environment:
         MYSQL_ROOT_PASSWORD: pass
         MYSQL_DATABASE: empmgmt
         MYSQL_USER: nitin
         MYSQL_PASSWORD: password
      volumes:
      - ../data/dev/mysql:/var/lib/mysql
      # Make sure that ../data/dev/mysql is emptry first time if you want to execute init scripts
      - ./initdb:/docker-entrypoint-initdb.d
   config-server:
      extends:
         file: ../common/docker-compose.yml
         service: config-server
      depends_on:
      - "discovery-server"
      environment:
      - jasypt.encryptor.password=jasy-config-app
      - spring.profiles.active=dev
   discovery-server:
      extends:
         file: ../common/docker-compose.yml
         service: discovery-server
      depends_on:
      - "db"
      - "kafka-1"
   zuul-api-gateway:
      extends:
         file: ../common/docker-compose.yml
         service: zuul-api-gateway
      depends_on:
      - "discovery-server"
      environment:
      - spring.profiles.active=dev