server:
  servlet:
    context-path: /asset
  port: 8090
spring:
  cloud:
    config:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asset
    username: nitin
    # \.m2\repository\org\jasypt\jasypt\1.9.2>java -cp ./jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input=password password=jasy-asset-app algorithm=PBEWithMD5AndDES
    password: ENC(fQvAPz53rOWgchG73p74MOPWbUwD/6ha)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibenate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#http://localhost:8761/eureka/apps/asset-management
eureka: 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'